# Listening port  
port = 6102 
# RPC listening port
rpc_port
# Minimum Coinswap amount
min_swap_amount = 100000
# Socks port
socks_port = 19050
# Directory server address
directory_server_address = 127.0.0.1:8080
# Fidelity Bond amount
fidelity_amount =  5000000
#  Fidelity Bond timelock in Block heights
fidelity_timelock = 26000
# Connection type
connection_type = TOR