# Network listening port
port= 8000
#Socks port
socks_port= 19070
# Directory server address
directory_server_address=bhbzkndgad52ojm75w4goii7xsi6ou73fzyvorxas7swg2snlto4c4ad.onion:8080
# Connection type
connection_type= TOR
# RPC port
rpc_port= 8081