on:
  push:
    branches:
      - master
  pull_request:

name: build

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    strategy:
      matrix:
        rust: [stable, nightly]
        features: [default, integration-test]
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Generate cache key
        run: echo "${{ runner.os }}-${{ matrix.rust }}-${{ matrix.features }}" | tee .cache_key

      - name: cache
        uses: actions/cache@v2
        with:
          path: |
            ~/.cargo/registry
            ~/.cargo/git
            target
          key: ${{ runner.os }}-cargo-${{ hashFiles('.cache_key') }}-${{ hashFiles('**/Cargo.toml','**/Cargo.lock') }}

      - name: Set default toolchain
        run: rustup default ${{ matrix.rust }}

      - name: Set profile
        run: rustup set profile minimal

      - name: Update toolchain
        run: rustup update

      - name: Build for OS
        run: cargo build --features=${{ matrix.features }}
