on: [push, pull_request]

name: Code Coverage

jobs:
  Code-coverage:
    name: Code coverage report
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Set default toolchain
        run: rustup default nightly
      - name: Set profile
        run: rustup set profile minimal

      - name: Run cargo test
        env:
          CARGO_INCREMENTAL: '0'
          RUSTFLAGS: '-Zprofile -Ccodegen-units=1 -Cinline-threshold=0 -Clink-dead-code -Coverflow-checks=off'
          RUSTDOCFLAGS: '-Zprofile -Ccodegen-units=1 -Cinline-threshold=0 -Clink-dead-code -Coverflow-checks=off'
        run: cargo test
      - id: coverage
        name: Generate coverage
        uses: actions-rs/grcov@v0.1.5
        
      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v1
        with:
          file: ${{ steps.coverage.outputs.report }}
          directory: ./coverage/reports/